name: Update Site and Tweet
on:
  push:
  workflow_dispatch:

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Build the site in the jekyll/builder container
#      run: |
#        docker run \
#        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
#        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

  tweet:
#    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: ethomson/send-tweet-action@v1
        with:
          status: Pathology Atlas and Notes for Medical Students See and Learn is updated on ${{ steps.date.outputs.date }}. See here https://www.patolojinotlari.com/ and here https://lab.patolojinotlari.com/
          consumer-key: ${{ secrets.API_KEY }}
          consumer-secret: ${{ secrets.API_SECRET_KEY }}
          access-token: ${{ secrets.ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
